language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5c1
before_install:
  - export PIP_FIND_LINKS=http://pypi.renie.fr/Django/
install:
  - pip install Django==$DJANGO_VERSION
script:
  - python setup.py test
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.3
